/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as PetRouteImport } from './routes/pet'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainPluginsRouteImport } from './routes/_main.plugins'
import { Route as MainScheduledRouteImport } from './routes/_main.scheduled'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsSectionRouteImport } from './routes/settings.$section'
import { Route as MainConversationSessionIdRouteImport } from './routes/_main.conversation.$sessionId'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const PetRoute = PetRouteImport.update({
  id: '/pet',
  path: '/pet',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainPluginsRoute = MainPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => MainRoute,
} as any)
const MainScheduledRoute = MainScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => MainRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSectionRoute = SettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SettingsRoute,
} as any)
const MainConversationSessionIdRoute =
  MainConversationSessionIdRouteImport.update({
    id: '/conversation/$sessionId',
    path: '/conversation/$sessionId',
    getParentRoute: () => MainRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/pet': typeof PetRoute
  '/settings': typeof SettingsRouteWithChildren
  '/plugins': typeof MainPluginsRoute
  '/scheduled': typeof MainScheduledRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/settings/': typeof SettingsIndexRoute
  '/conversation/$sessionId': typeof MainConversationSessionIdRoute
}
export interface FileRoutesByTo {
  '/pet': typeof PetRoute
  '/plugins': typeof MainPluginsRoute
  '/scheduled': typeof MainScheduledRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/': typeof MainIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/conversation/$sessionId': typeof MainConversationSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/pet': typeof PetRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_main/plugins': typeof MainPluginsRoute
  '/_main/scheduled': typeof MainScheduledRoute
  '/settings/$section': typeof SettingsSectionRoute
  '/_main/': typeof MainIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_main/conversation/$sessionId': typeof MainConversationSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pet'
    | '/settings'
    | '/plugins'
    | '/scheduled'
    | '/settings/$section'
    | '/settings/'
    | '/conversation/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pet'
    | '/plugins'
    | '/scheduled'
    | '/settings/$section'
    | '/'
    | '/settings'
    | '/conversation/$sessionId'
  id:
    | '__root__'
    | '/_main'
    | '/pet'
    | '/settings'
    | '/_main/plugins'
    | '/_main/scheduled'
    | '/settings/$section'
    | '/_main/'
    | '/settings/'
    | '/_main/conversation/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  PetRoute: typeof PetRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet': {
      id: '/pet'
      path: '/pet'
      fullPath: '/pet'
      preLoaderRoute: typeof PetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/plugins': {
      id: '/_main/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof MainPluginsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/scheduled': {
      id: '/_main/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof MainScheduledRouteImport
      parentRoute: typeof MainRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/$section': {
      id: '/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof SettingsSectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_main/conversation/$sessionId': {
      id: '/_main/conversation/$sessionId'
      path: '/conversation/$sessionId'
      fullPath: '/conversation/$sessionId'
      preLoaderRoute: typeof MainConversationSessionIdRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainPluginsRoute: typeof MainPluginsRoute
  MainScheduledRoute: typeof MainScheduledRoute
  MainIndexRoute: typeof MainIndexRoute
  MainConversationSessionIdRoute: typeof MainConversationSessionIdRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainPluginsRoute: MainPluginsRoute,
  MainScheduledRoute: MainScheduledRoute,
  MainIndexRoute: MainIndexRoute,
  MainConversationSessionIdRoute: MainConversationSessionIdRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface SettingsRouteChildren {
  SettingsSectionRoute: typeof SettingsSectionRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsSectionRoute: SettingsSectionRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  PetRoute: PetRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
