/**
 * @openharness/client 公共导出。
 *
 * 面向 TUI / Web / Desktop：typed HTTP API、SSE 解析、事件 reducer、replay+live 同步。
 * 客户端只做展示与控制，不拥有 agent runtime。
 */

export {
  createPromptRequestId,
  normalizeDaemonBaseUrl,
  OpenHarnessApiError,
  IncompatibleProtocolError,
  OpenHarnessClient,
  streamServerSentEvents,
} from "./transport/index.js";
export type {
  AttachmentAssetRecord,
  ClientProtocolSupport,
  ProtocolCompatibility,
  ServerCapabilities,
} from "@openharness/protocol";
export {
  checkProtocolCompatibility,
  supportsFeature,
} from "@openharness/protocol";
export {
  applyEvent,
  applyEvents,
  applySessionSnapshot,
  createInitialClientState,
  hydrateState,
  selectSessionMessagesWithParts,
  syncEvents,
  UnsupportedSessionEventSchemaVersionError,
} from "./state/index.js";
export {
  LOCAL_COMMAND_DETAILS,
  LOCAL_COMMAND_NAMES,
  dispatchSessionCommand,
  hasActiveRun,
  mergeCommandDetails,
  parseSlashLine,
  resolveSessionCwd,
} from "./commands/index.js";
export {
  patchSessionRuntimeMetadata,
  readRuntimeMetadata,
  readSessionRuntimeConfig,
} from "@openharness/protocol";
export type {
  SessionRuntimeConfig,
  SessionRuntimeConfigPatch,
} from "@openharness/protocol";
export type {
  PresentationReadRequest,
  SessionCommandHost,
  SessionCommandOutcome,
  SlashLine,
} from "./commands/index.js";
export type {
  AdmitClientPromptInput,
  AgentPersonaInfo,
  AuthStatus,
  CommandCatalogEntry,
  CommandKind,
  CommandSource,
  CompactSessionResponse,
  CancelQueuedClientPromptInput,
  CancelQueuedPromptResponse,
  CreateBackgroundShellInput,
  CreateBackgroundShellResult,
  CreateScheduledTaskInput,
  CreateClientSessionInput,
  EditLatestClientPromptInput,
  EventSyncOptions,
  ForkClientSessionInput,
  HookInfo,
  ReloadPluginsResponse,
  RewindSessionResponse,
  InputDelivery,
  InterruptSessionResponse,
  InvokeClientCommandInput,
  InvokeCommandResponse,
  ListClientMessagePartsOptions,
  ListCommandsOptions,
  ListEventsOptions,
  ListMessagesOptions,
  ListPermissionsOptions,
  ListSessionsOptions,
  ListProjectsOptions,
  ProjectRecord,
  McpServerStatus,
  MemoryEntryRecord,
  MemoryListResponse,
  ModelInfo,
  ModelProviderInfo,
  OpenHarnessClientOptions,
  OpenHarnessClientState,
  OpenHarnessServerHealth,
  OutputStyleInfo,
  PermissionRequestRecord,
  PermissionStatus,
  PluginInfo,
  PromoteQueuedClientPromptInput,
  PromoteQueuedPromptResponse,
  PromptResponse,
  ProviderInfo,
  CustomProviderInput,
  RememberSessionResponse,
  ReplyPermissionInput,
  ScheduledRunRecord,
  ScheduledTaskRecord,
  ScheduledTaskStatusSummary,
  SessionBucket,
  UpdateScheduledTaskInput,
  SessionEventRecord,
  SessionExportResponse,
  SessionInputRecord,
  SessionMessagePartRecord,
  SessionMessageRecord,
  SessionRecord,
  SessionRunRecord,
  SessionRunAttemptRecord,
  SessionExecutionRecord,
  SessionStateSnapshot,
  SessionUsageResponse,
  StartDreamResponse,
  SyncEventUpdate,
  UpdateClientSessionInput,
  UploadAttachmentInput,
  DownloadAttachmentOptions,
} from "./types/index.js";
export type { SessionMessageWithParts } from "./state/index.js";
export type {
  TerminalCreateRequest,
  TerminalEvent,
  TerminalReadRequest,
  TerminalReadResult,
  TerminalResizeRequest,
  TerminalRuntime,
  TerminalSessionInfo,
  TerminalSessionStatus,
  TerminalSignal,
  TerminalSource,
  TerminalWriteRequest,
  JobCapabilities,
  JobKind,
  JobReadResult,
  JobSnapshot,
  JobStatus,
  JobWaitResult,
  DurableChannelMessageInput,
  DurableChannelMessageResult,
  ExternalConversationRecord,
  ChannelDeliveryRecord,
  ChannelDeliveryStatus,
  ChannelStatusSnapshot,
  RecordChannelDeliveryInput,
} from "@openharness/protocol";
