import { ToolRegistry } from "@openharness/core";
import { bashTool } from "./shell/bash";
import { fileReadTool } from "./file/read";
import { fileWriteTool } from "./file/write";
import { fileEditTool } from "./file/edit";
import { globTool } from "./file/glob";
import { grepTool } from "./search/grep";
import { webFetchTool } from "./web/fetch";
import { webSearchTool } from "./web/search";
import { todoWriteTool } from "./meta/todo-write";
import { configTool } from "./meta/config";
import { sleepTool } from "./meta/sleep";
import { skillTool } from "./meta/skill";
import { toolSearchTool } from "./meta/tool-search";
import { askUserTool } from "./meta/ask-user";
import { briefTool } from "./meta/brief";
import { taskCreateTool, taskGetTool, taskListTool, taskOutputTool, taskStopTool } from "./task";
import { enterPlanModeTool, exitPlanModeTool } from "./mode/plan-mode";
import { enterWorktreeTool, exitWorktreeTool } from "./mode/worktree";
import { notebookEditTool } from "./notebook";
import { agentTool, sendMessageTool } from "./agent";
import { teamCreateTool, teamDeleteTool } from "./agent/team";
import { cronCreateTool, cronDeleteTool, cronListTool, cronToggleTool } from "./schedule";
import { mcpToolCallTool, listMcpResourcesTool, readMcpResourceTool } from "./mcp";
import { lspTool } from "./search/lsp";

export function createDefaultToolRegistry(): ToolRegistry {
  const registry = new ToolRegistry();
  registry.register(bashTool);
  registry.register(fileReadTool);
  registry.register(fileWriteTool);
  registry.register(fileEditTool);
  registry.register(globTool);
  registry.register(grepTool);
  registry.register(webFetchTool);
  registry.register(webSearchTool);
  registry.register(todoWriteTool);
  registry.register(configTool);
  registry.register(sleepTool);
  registry.register(skillTool);
  registry.register(toolSearchTool);
  registry.register(askUserTool);
  registry.register(briefTool);
  registry.register(taskCreateTool);
  registry.register(taskGetTool);
  registry.register(taskListTool);
  registry.register(taskOutputTool);
  registry.register(taskStopTool);
  registry.register(enterPlanModeTool);
  registry.register(exitPlanModeTool);
  registry.register(enterWorktreeTool);
  registry.register(exitWorktreeTool);
  registry.register(notebookEditTool);
  registry.register(agentTool);
  registry.register(sendMessageTool);
  registry.register(teamCreateTool);
  registry.register(teamDeleteTool);
  registry.register(cronCreateTool);
  registry.register(cronDeleteTool);
  registry.register(cronListTool);
  registry.register(cronToggleTool);
  registry.register(mcpToolCallTool);
  registry.register(listMcpResourcesTool);
  registry.register(readMcpResourceTool);
  registry.register(lspTool);
  return registry;
}
